export type AgentGuardReceiverExampleId = "nextjs" | "express" | "fastapi";

export type AgentGuardReceiverChecklistItem = {
  title: string;
  detail: string;
};

export type AgentGuardReceiverExample = {
  id: AgentGuardReceiverExampleId;
  label: string;
  language: "typescript" | "python";
  runtime: string;
  summary: string;
  code: string;
};

export const AGENT_GUARD_RECEIVER_CHECKLIST: AgentGuardReceiverChecklistItem[] = [
  {
    title: "Use HTTPS",
    detail: "Configure an externally reachable HTTPS endpoint and keep test receivers separate from production receivers.",
  },
  {
    title: "Store the signing secret server-side",
    detail: "Save the one-time ShadowGuard destination secret in a receiver-side secret store or environment variable.",
  },
  {
    title: "Verify the ShadowGuard headers",
    detail: "Require x-shadowguard-event-id, x-shadowguard-timestamp, and x-shadowguard-signature on every request.",
  },
  {
    title: "Check timestamp tolerance",
    detail: "Reject stale events outside a short clock-skew window, such as five minutes.",
  },
  {
    title: "Verify HMAC over canonical JSON",
    detail: "Parse the payload, canonicalize JSON with sorted object keys, and compare the HMAC-SHA256 digest using timing-safe comparison.",
  },
  {
    title: "Track event IDs",
    detail: "Store accepted event IDs and treat duplicates as idempotent replays.",
  },
  {
    title: "Handle metadata only",
    detail: "Persist event ID, risk, classification, source, and content length. AgentGuard export payloads do not include raw prompts, responses, files, or messages.",
  },
  {
    title: "Return 2xx after acceptance",
    detail: "Return a 2xx only after the receiver has verified and accepted the event.",
  },
];

const NEXTJS_RECEIVER_EXAMPLE = [
  'import { createHmac, timingSafeEqual } from "node:crypto";',
  "",
  "const SIGNING_SECRET = process.env.AGENTGUARD_EXPORT_SIGNING_SECRET ?? \"\";",
  "const TOLERANCE_SECONDS = 300;",
  "const acceptedEventIds = new Set<string>(); // Replace with durable storage.",
  "",
  "function canonicalJson(value: unknown): string {",
  "  if (value === null || typeof value !== \"object\") return JSON.stringify(value);",
  "  if (Array.isArray(value)) return `[${value.map(canonicalJson).join(\",\")}]`;",
  "  return `{${Object.entries(value as Record<string, unknown>)",
  "    .filter(([, nested]) => nested !== undefined)",
  "    .sort(([left], [right]) => left.localeCompare(right))",
  "    .map(([key, nested]) => `${JSON.stringify(key)}:${canonicalJson(nested)}`)",
  "    .join(\",\")}}`;",
  "}",
  "",
  "function sign(payload: unknown): string {",
  "  // HMAC-SHA256 over ShadowGuard canonical JSON.",
  "  return createHmac(\"sha256\", SIGNING_SECRET)",
  "    .update(canonicalJson(payload), \"utf8\")",
  "    .digest(\"hex\");",
  "}",
  "",
  "function timingSafeHexEqual(leftHex: string, rightHex: string): boolean {",
  "  const left = Buffer.from(leftHex, \"hex\");",
  "  const right = Buffer.from(rightHex, \"hex\");",
  "  return left.length === right.length && timingSafeEqual(left, right);",
  "}",
  "",
  "export async function POST(request: Request) {",
  "  const eventId = request.headers.get(\"x-shadowguard-event-id\");",
  "  const timestamp = Number(request.headers.get(\"x-shadowguard-timestamp\"));",
  "  const signature = request.headers.get(\"x-shadowguard-signature\");",
  "  if (!eventId || !Number.isFinite(timestamp) || !signature) {",
  "    return Response.json({ error: \"missing_signature_headers\" }, { status: 401 });",
  "  }",
  "",
  "  const skewSeconds = Math.abs(Math.floor(Date.now() / 1000) - timestamp);",
  "  if (skewSeconds > TOLERANCE_SECONDS) {",
  "    return Response.json({ error: \"stale_event\" }, { status: 401 });",
  "  }",
  "",
  "  const payload = await request.json();",
  "  if (!timingSafeHexEqual(sign(payload), signature)) {",
  "    return Response.json({ error: \"bad_signature\" }, { status: 401 });",
  "  }",
  "",
  "  if (acceptedEventIds.has(eventId)) {",
  "    return Response.json({ ok: true, duplicate: true });",
  "  }",
  "",
  "  acceptedEventIds.add(eventId);",
  "  // Persist metadata such as payload.activity.riskLevel, dataClassification,",
  "  // source, and contentLength. AgentGuard exports do not include raw prompts.",
  "  return Response.json({ ok: true });",
  "}",
].join("\n");

const EXPRESS_RECEIVER_EXAMPLE = [
  'import express from "express";',
  'import { createHmac, timingSafeEqual } from "node:crypto";',
  "",
  "const app = express();",
  "const SIGNING_SECRET = process.env.AGENTGUARD_EXPORT_SIGNING_SECRET ?? \"\";",
  "const acceptedEventIds = new Set(); // Replace with durable storage.",
  "",
  "app.use(express.json());",
  "",
  "function canonicalJson(value) {",
  "  if (value === null || typeof value !== \"object\") return JSON.stringify(value);",
  "  if (Array.isArray(value)) return `[${value.map(canonicalJson).join(\",\")}]`;",
  "  return `{${Object.entries(value)",
  "    .filter(([, nested]) => nested !== undefined)",
  "    .sort(([left], [right]) => left.localeCompare(right))",
  "    .map(([key, nested]) => `${JSON.stringify(key)}:${canonicalJson(nested)}`)",
  "    .join(\",\")}}`;",
  "}",
  "",
  "function sign(payload) {",
  "  // HMAC-SHA256 over ShadowGuard canonical JSON.",
  "  return createHmac(\"sha256\", SIGNING_SECRET)",
  "    .update(canonicalJson(payload), \"utf8\")",
  "    .digest(\"hex\");",
  "}",
  "",
  "function timingSafeHexEqual(leftHex, rightHex) {",
  "  const left = Buffer.from(leftHex, \"hex\");",
  "  const right = Buffer.from(rightHex, \"hex\");",
  "  return left.length === right.length && timingSafeEqual(left, right);",
  "}",
  "",
  "app.post(\"/agentguard/events\", (req, res) => {",
  "  const eventId = req.header(\"x-shadowguard-event-id\");",
  "  const timestamp = Number(req.header(\"x-shadowguard-timestamp\"));",
  "  const signature = req.header(\"x-shadowguard-signature\");",
  "  if (!eventId || !Number.isFinite(timestamp) || !signature) {",
  "    return res.status(401).json({ error: \"missing_signature_headers\" });",
  "  }",
  "",
  "  const skewSeconds = Math.abs(Math.floor(Date.now() / 1000) - timestamp);",
  "  if (skewSeconds > 300) return res.status(401).json({ error: \"stale_event\" });",
  "  if (!timingSafeHexEqual(sign(req.body), signature)) {",
  "    return res.status(401).json({ error: \"bad_signature\" });",
  "  }",
  "",
  "  if (acceptedEventIds.has(eventId)) return res.json({ ok: true, duplicate: true });",
  "  acceptedEventIds.add(eventId);",
  "  // Store metadata and contentLength. Do not expect raw prompt or response content.",
  "  return res.json({ ok: true });",
  "});",
].join("\n");

const FASTAPI_RECEIVER_EXAMPLE = [
  "import hashlib",
  "import hmac",
  "import json",
  "import os",
  "import time",
  "from fastapi import FastAPI, Header, HTTPException, Request",
  "",
  "app = FastAPI()",
  "SIGNING_SECRET = os.environ[\"AGENTGUARD_EXPORT_SIGNING_SECRET\"]",
  "accepted_event_ids: set[str] = set()  # Replace with durable storage.",
  "",
  "def canonical_json(value) -> str:",
  "    return json.dumps(value, sort_keys=True, separators=(\",\", \":\"))",
  "",
  "def sign(payload) -> str:",
  "    # HMAC-SHA256 over ShadowGuard canonical JSON.",
  "    return hmac.new(",
  "        SIGNING_SECRET.encode(\"utf-8\"),",
  "        canonical_json(payload).encode(\"utf-8\"),",
  "        hashlib.sha256,",
  "    ).hexdigest()",
  "",
  "@app.post(\"/agentguard/events\")",
  "# FastAPI maps x-shadowguard-event-id, x-shadowguard-timestamp,",
  "# and x-shadowguard-signature into the underscore parameters below.",
  "async def receive_agentguard_event(",
  "    request: Request,",
  "    x_shadowguard_event_id: str | None = Header(default=None),",
  "    x_shadowguard_timestamp: str | None = Header(default=None),",
  "    x_shadowguard_signature: str | None = Header(default=None),",
  "):",
  "    if not x_shadowguard_event_id or not x_shadowguard_timestamp or not x_shadowguard_signature:",
  "        raise HTTPException(status_code=401, detail=\"missing_signature_headers\")",
  "",
  "    try:",
  "        timestamp = int(x_shadowguard_timestamp)",
  "    except ValueError:",
  "        raise HTTPException(status_code=401, detail=\"bad_timestamp\")",
  "",
  "    if abs(int(time.time()) - timestamp) > 300:",
  "        raise HTTPException(status_code=401, detail=\"stale_event\")",
  "",
  "    payload = await request.json()",
  "    expected = sign(payload)",
  "    if not hmac.compare_digest(expected, x_shadowguard_signature):",
  "        raise HTTPException(status_code=401, detail=\"bad_signature\")",
  "",
  "    if x_shadowguard_event_id in accepted_event_ids:",
  "        return {\"ok\": True, \"duplicate\": True}",
  "",
  "    accepted_event_ids.add(x_shadowguard_event_id)",
  "    # Persist metadata and contentLength. Raw AI prompts, responses, files, and messages are not exported.",
  "    return {\"ok\": True}",
].join("\n");

export const AGENT_GUARD_RECEIVER_EXAMPLES: AgentGuardReceiverExample[] = [
  {
    id: "nextjs",
    label: "Next.js Route Handler",
    language: "typescript",
    runtime: "Next.js / Node runtime",
    summary: "Use this for a receiver implemented as an App Router route handler.",
    code: NEXTJS_RECEIVER_EXAMPLE,
  },
  {
    id: "express",
    label: "Express",
    language: "typescript",
    runtime: "Node.js / Express",
    summary: "Use this for a customer-controlled Express receiver.",
    code: EXPRESS_RECEIVER_EXAMPLE,
  },
  {
    id: "fastapi",
    label: "Python FastAPI",
    language: "python",
    runtime: "Python / FastAPI",
    summary: "Use this for a Python receiver service.",
    code: FASTAPI_RECEIVER_EXAMPLE,
  },
];
